---
- hosts: localhost
  become_user: root
  tasks:
     - name: stop previous version docker
       docker_container:
        name: flask_app
        image: chr93/trg_demo:latest
        shell: docker run -d --name flask_demo -p 5000:5000 chr93/trg_demo:latest

